Repository KOSTA-devops-2team/Wedder, pull requests merged in 2024-10, with the labels that each got.

#41 [PR] BE - 결제시스템 구현 완료
  src/main/java/kr/co/wedder/customer/controller/LoginController.java
  src/main/java/kr/co/wedder/customer/dao/CustomerDaoImpl.java
  src/main/java/kr/co/wedder/customer/domain/CustomerDTO.java
  src/main/java/kr/co/wedder/payment/controller/PaymentRestController.java
  src/main/java/kr/co/wedder/payment/dao/PaymentDao.java
  src/main/java/kr/co/wedder/payment/dao/PaymentDaoImpl.java
  src/main/java/kr/co/wedder/payment/domain/PaymentDto.java
  src/main/java/kr/co/wedder/payment/domain/PaymentRequest.java
  src/main/java/kr/co/wedder/payment/service/PaymentService.java
  src/main/java/kr/co/wedder/payment/service/PaymentServiceImpl.java
  src/main/java/kr/co/wedder/sdmpackage/controller/PackageController.java
  src/main/java/kr/co/wedder/sdmpackage/dao/PackageDaoImpl.java
  src/main/java/kr/co/wedder/sdmpackage/domain/PackageDto.java
  src/main/resources/mapper/PaymentMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/views/package/packageDetail.jsp
  src/main/webapp/WEB-INF/views/package/packageRecommend.jsp
  src/main/webapp/resources/js/package/packagePayment.js
Labels: 🕹️ feature, hyewon

#45 [PR] BE - 패키지 예약(날짜, 시간)
  .idea/dataSources.xml
  .idea/runConfigurations/_template__of_Local.xml
  src/main/java/kr/co/wedder/calendar/domain/CompanyScheduleDto.java
  src/main/java/kr/co/wedder/customer/controller/LoginController.java
  src/main/java/kr/co/wedder/estimate/controller/EstimateController.java
  src/main/java/kr/co/wedder/payment/controller/PaymentRestController.java
  src/main/java/kr/co/wedder/sdmpackage/controller/PackageController.java
  src/main/java/kr/co/wedder/sdmpackage/controller/PackageRestController.java
  src/main/java/kr/co/wedder/sdmpackage/dao/PackageDao.java
  src/main/java/kr/co/wedder/sdmpackage/dao/PackageDaoImpl.java
  src/main/java/kr/co/wedder/sdmpackage/service/PackageService.java
  src/main/java/kr/co/wedder/sdmpackage/service/PackageServiceImpl.java
  src/main/resources/mapper/PackageMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/views/common/calendarList.jsp
  src/main/webapp/WEB-INF/views/package/packageCalendar.jsp
  src/main/webapp/WEB-INF/views/package/packageDetail.jsp
  src/main/webapp/WEB-INF/views/user/loginForm.jsp
  src/main/webapp/resources/css/mypage/reservationDetail.css
  src/main/webapp/resources/css/package/packageCalendar.css
  src/main/webapp/resources/css/package/packageDetail.css
  src/main/webapp/resources/js/mypage/calendar.js
  src/main/webapp/resources/js/package/packageCalender.js
  src/main/webapp/resources/js/package/packagePayment.js
Labels: 🕹️ feature, hyewon

#48 [PR] BE : 견적서 옵션선택 페이지 완성 및 최종페이지 진행
  .idea/dataSources.xml
  .idea/webContexts.xml
  src/main/java/kr/co/wedder/customer/controller/LoginController.java
  src/main/java/kr/co/wedder/customer/controller/RegisterController.java
  src/main/java/kr/co/wedder/customer/dao/CustomerDao.java
  src/main/java/kr/co/wedder/customer/dao/CustomerDaoImpl.java
  src/main/java/kr/co/wedder/customer/domain/CustomerDTO.java
  src/main/java/kr/co/wedder/customer/domain/CustomerDto.java
  src/main/java/kr/co/wedder/customer/service/CustomerService.java
  src/main/java/kr/co/wedder/customer/service/CustomerServiceImpl.java
  src/main/java/kr/co/wedder/estimate/controller/EstimateController.java
  src/main/java/kr/co/wedder/estimate/dao/EstimateDao.java
  src/main/java/kr/co/wedder/estimate/dao/EstimateDaoImpl.java
  src/main/java/kr/co/wedder/estimate/domain/EstimateDto.java
  src/main/java/kr/co/wedder/estimate/service/EstimateService.java
  src/main/java/kr/co/wedder/estimate/service/EstimateServiceImpl.java
  src/main/resources/mapper/CustomerMapper.xml
  src/main/resources/mapper/EstimateMapper.xml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/views/customer/loginForm.jsp
  src/main/webapp/WEB-INF/views/customer/registerForm.jsp
  src/main/webapp/WEB-INF/views/estimate/estimateCompany.jsp
  src/main/webapp/WEB-INF/views/estimate/estimateOption.jsp
  src/main/webapp/WEB-INF/views/estimate/estimateTotal.jsp
  src/main/webapp/WEB-INF/views/user/consentForm.jsp
  src/main/webapp/WEB-INF/views/user/emailVertify.jsp
  src/main/webapp/resources/css/customer/login.css
  src/main/webapp/resources/css/customer/signUp.css
  src/main/webapp/resources/css/estimate/estimateCompany.css
  src/main/webapp/resources/css/estimate/estimateOption.css
  src/main/webapp/resources/css/estimate/estimateTotal.css
  src/main/webapp/resources/css/user/consentForm.css
  src/main/webapp/resources/css/user/emailVertify.css
  src/main/webapp/resources/js/customer/login.js
  src/main/webapp/resources/js/customer/signUp.js
  src/main/webapp/resources/js/estimate/estimateCompany.js
  src/main/webapp/resources/js/estimate/estimateOption.js
  src/main/webapp/resources/js/estimate/estimateTotal.js
  src/main/webapp/resources/js/user/consentForm.js
  src/main/webapp/resources/js/user/emailVertify.js
  src/test/java/kr/co/wedder/customer/dao/customerDaoTest.java
Labels: 🕹️ feature, junseok

#49 [PR] BE - 페이지네이션 기능
  .idea/dataSources.xml
  .idea/webContexts.xml
  src/main/java/kr/co/wedder/company/controller/HallController.java
  src/main/java/kr/co/wedder/company/controller/HallRestController.java
  src/main/java/kr/co/wedder/company/controller/SDMController.java
  src/main/java/kr/co/wedder/company/dao/CompanyDao.java
  src/main/java/kr/co/wedder/company/dao/CompanyDaoImpl.java
  src/main/java/kr/co/wedder/company/domain/CompanyDto.java
  src/main/java/kr/co/wedder/company/domain/HallDto.java
  src/main/java/kr/co/wedder/company/domain/MakeupDto.java
  src/main/java/kr/co/wedder/company/domain/Pagination.java
  src/main/java/kr/co/wedder/company/domain/SearchItem.java
  src/main/java/kr/co/wedder/company/domain/StudioDto.java
  src/main/java/kr/co/wedder/company/service/CompanyService.java
  src/main/java/kr/co/wedder/company/service/CompanyServiceImpl.java
  src/main/resources/mapper/CompanyMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/common/mapApi.jsp
  src/main/webapp/WEB-INF/views/common/pagination.jsp
  src/main/webapp/WEB-INF/views/company/studio/studioList.jsp
  src/main/webapp/WEB-INF/views/company/weddinghall/weddinghallDetail.jsp
  src/main/webapp/WEB-INF/views/company/weddinghall/weddinghallList.jsp
  src/main/webapp/resources/css/common/mapApi.css
  src/main/webapp/resources/css/common/pagination/pagination.css
  src/main/webapp/resources/css/company/weddinghall/weddinghallDetail.css
  src/main/webapp/resources/css/company/weddinghall/weddinghallList.css
  src/main/webapp/resources/js/company/weddinghall/mapApi.js
  src/main/webapp/resources/js/company/weddinghall/weddinghallDetail.js
  src/main/webapp/resources/js/company/weddinghall/weddinghallList.js
  src/main/webapp/resources/js/pagination/pagination.js
Labels: 🕹️ feature, jeonghwa

#50 [PR] BE - 깃 머징
  .idea/vcs.xml
  src/main/java/kr/co/wedder/mypage/controller/MyPageController.java
  src/main/java/kr/co/wedder/mypage/controller/MyPageRestController.java
  src/main/java/kr/co/wedder/mypage/dao/MyPageDao.java
  src/main/java/kr/co/wedder/mypage/dao/MyPageDaoImpl.java
  src/main/java/kr/co/wedder/mypage/domain/EstimateDto.java
  src/main/java/kr/co/wedder/mypage/domain/EstimateInfoDto.java
  src/main/java/kr/co/wedder/mypage/domain/VisitCriteria.java
  src/main/java/kr/co/wedder/mypage/service/MyPageService.java
  src/main/java/kr/co/wedder/mypage/service/MyPageServiceImpl.java
  src/main/resources/mapper/MyPageMapper.xml
  src/main/webapp/WEB-INF/views/common/calendarList.jsp
  src/main/webapp/WEB-INF/views/common/navibar.jsp
  src/main/webapp/WEB-INF/views/mypage/estimateStorage.jsp
  src/main/webapp/WEB-INF/views/mypage/myPayment.jsp
  src/main/webapp/WEB-INF/views/mypage/paymentDetail.jsp
  src/main/webapp/WEB-INF/views/mypage/reservationDetail.jsp
  src/main/webapp/WEB-INF/views/mypage/reservationList.jsp
  src/main/webapp/resources/css/common/calendarList.css
  src/main/webapp/resources/css/mypage/calendar.css
  src/main/webapp/resources/css/mypage/myPayment.css
  src/main/webapp/resources/css/mypage/mypageNaviba.css
  src/main/webapp/resources/css/mypage/reservationDetail.css
  src/main/webapp/resources/css/mypage/reservationList.css
  src/main/webapp/resources/js/mypage/calendar.js
  src/main/webapp/resources/js/mypage/estimateStorage.js
  src/main/webapp/resources/js/mypage/myPayment.js
  src/main/webapp/resources/js/mypage/navibar.js
  src/main/webapp/resources/js/mypage/reservationDetail.js
  src/main/webapp/resources/js/mypage/reservationList.js
  src/test/java/kr/co/wedder/calendar/controller/CalendarControllerTest.java
  src/test/java/kr/co/wedder/calendar/dao/CalendarDaoImplTest.java
  src/test/java/kr/co/wedder/calendar/service/CalendarServiceImplTest.java
  src/test/java/kr/co/wedder/customerDaoTest.java
  src/test/java/kr/co/wedder/mypage/dao/MyPageDaoImplTest.java
  src/test/java/kr/co/wedder/mypage/service/MyPageServiceImplTest.java
Labels: 🕹️ feature, jongwon

#52 [PR] BE - CSS 수정 및 모달창 변경
  .idea/jsLibraryMappings.xml
  src/main/webapp/WEB-INF/views/estimate/estimateCompany.jsp
  src/main/webapp/WEB-INF/views/estimate/estimateTotal.jsp
  src/main/webapp/resources/css/estimate/estimateCompany.css
  src/main/webapp/resources/css/estimate/estimateOption.css
  src/main/webapp/resources/css/estimate/estimateTotal.css
  src/main/webapp/resources/js/estimate/estimateTotal.js
Labels: 🕹️ feature, junseok

#53 [PR] BE - 결제 트랜잭션
  src/main/java/kr/co/wedder/mypage/domain/ReservationDto.java
  src/main/java/kr/co/wedder/payment/controller/PaymentRestController.java
  src/main/java/kr/co/wedder/payment/dao/PaymentDao.java
  src/main/java/kr/co/wedder/payment/dao/PaymentDaoImpl.java
  src/main/java/kr/co/wedder/payment/domain/PaymentDto.java
  src/main/java/kr/co/wedder/payment/domain/PaymentRequest.java
  src/main/java/kr/co/wedder/payment/service/PaymentService.java
  src/main/java/kr/co/wedder/payment/service/PaymentServiceImpl.java
  src/main/java/kr/co/wedder/reservation/sdm/dao/ReservationDao.java
  src/main/java/kr/co/wedder/reservation/sdm/dao/ReservationDaoImpl.java
  src/main/java/kr/co/wedder/sdmpackage/domain/PackageDetailDto.java
  src/main/resources/application.properties
  src/main/resources/mapper/CalendarMapper.xml
  src/main/resources/mapper/PackageMapper.xml
  src/main/resources/mapper/ReservationMapper.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/customer/loginForm.jsp
  src/main/webapp/WEB-INF/views/package/packageCalendar.jsp
  src/main/webapp/WEB-INF/views/package/packageDetail.jsp
  src/main/webapp/WEB-INF/views/package/packageMain.jsp
  src/main/webapp/WEB-INF/views/package/packageRecommend.jsp
  src/main/webapp/resources/css/package/packageMain.css
  src/main/webapp/resources/css/package/packageRecommend.css
  src/main/webapp/resources/js/main/main.js
  src/main/webapp/resources/js/package/packageCalender.js
  src/main/webapp/resources/js/package/packageMain.js
  src/main/webapp/resources/js/package/packagePayment.js
  src/main/webapp/resources/js/package/packageRecommend.js
Labels: 🕹️ feature, hyewon

#55 [PR] BE - 마이 페이지 견적함 및 css 스타일 수정
  src/main/java/kr/co/wedder/mypage/controller/MyPageController.java
  src/main/java/kr/co/wedder/mypage/dao/MyPageDao.java
  src/main/java/kr/co/wedder/mypage/dao/MyPageDaoImpl.java
  src/main/java/kr/co/wedder/mypage/service/MyPageService.java
  src/main/java/kr/co/wedder/mypage/service/MyPageServiceImpl.java
  src/main/resources/mapper/MyPageMapper.xml
  src/main/webapp/WEB-INF/views/common/sidebarMyPage.jsp
  src/main/webapp/WEB-INF/views/mypage/estimateStorage.jsp
  src/main/webapp/WEB-INF/views/mypage/likeList.jsp
  src/main/webapp/WEB-INF/views/mypage/myPayment.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/WEB-INF/views/mypage/reservationList.jsp
  src/main/webapp/resources/css/mypage/estimateStorage.css
  src/main/webapp/resources/css/mypage/mypage.css
  src/main/webapp/resources/css/mypage/reservationDetail.css
  src/main/webapp/resources/css/mypage/reservationList.css
Labels: 🕹️ feature, jongwon

#57 [PR] - BE pagination page오류 해결
  src/main/java/kr/co/wedder/company/controller/SDMController.java
  src/main/resources/mapper/CompanyMapper.xml
  src/main/webapp/WEB-INF/views/company/studio/studioList.jsp
  src/main/webapp/resources/js/company/studio/studioList.js
Labels: 🐞 bug, jeonghwa

#61 [PR] BE - Estimate 가격표시 수정
  src/main/resources/mapper/EstimateMapper.xml
  src/main/webapp/WEB-INF/views/estimate/estimateCompany.jsp
  src/main/webapp/WEB-INF/views/estimate/estimateOption.jsp
  src/main/webapp/WEB-INF/views/estimate/estimateTotal.jsp
  src/main/webapp/resources/css/estimate/estimateCompany.css
Labels: 🕹️ feature, junseok

#62 [PR] BE - Bugfix
  src/main/java/kr/co/wedder/sdmpackage/controller/PackageController.java
  src/main/java/kr/co/wedder/sdmpackage/controller/PackageRestController.java
  src/main/java/kr/co/wedder/sdmpackage/domain/PackageDetailDto.java
  src/main/resources/mapper/PackageMapper.xml
  src/main/webapp/WEB-INF/views/package/packageDetail.jsp
  src/main/webapp/WEB-INF/views/package/packageRecommend.jsp
  src/main/webapp/resources/css/package/packageRecommend.css
  src/main/webapp/resources/js/package/packageRecommend.js
Labels: 🕹️ feature, hyewon

#63 [PR] BE - 업체 검색 페이징 수정
  src/main/java/kr/co/wedder/company/controller/HallController.java
  src/main/java/kr/co/wedder/company/controller/HallRestController.java
  src/main/java/kr/co/wedder/company/controller/SDMController.java
  src/main/java/kr/co/wedder/company/controller/SDMRestController.java
  src/main/java/kr/co/wedder/company/dao/CompanyDao.java
  src/main/java/kr/co/wedder/company/dao/CompanyDaoImpl.java
  src/main/java/kr/co/wedder/company/service/CompanyService.java
  src/main/java/kr/co/wedder/company/service/CompanyServiceImpl.java
  src/main/resources/mapper/CompanyMapper.xml
  src/main/webapp/WEB-INF/views/common/mapApi.jsp
  src/main/webapp/WEB-INF/views/company/dress/dressList.jsp
  src/main/webapp/WEB-INF/views/company/makeup/makeupList.jsp
  src/main/webapp/WEB-INF/views/company/studio/studioDetail.jsp
  src/main/webapp/WEB-INF/views/company/studio/studioList.jsp
  src/main/webapp/WEB-INF/views/company/weddinghall/weddinghallDetail.jsp
  src/main/webapp/WEB-INF/views/company/weddinghall/weddinghallList.jsp
  src/main/webapp/resources/css/company/dress/dressList.css
  src/main/webapp/resources/css/company/makeup/makeupList.css
  src/main/webapp/resources/js/company/studio/studioList.js
  src/main/webapp/resources/js/company/weddinghall/mapApi.js
  src/main/webapp/resources/js/company/weddinghall/weddinghallList.js
  src/main/webapp/resources/js/map/mapApi.js
  src/main/webapp/resources/js/pagination/hallPagination.js
Labels: 🐞 bug, jeonghwa

#65 [PR] BE - 로그인, 견적서 디자인 및 오류 수정
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/customer/registerForm.jsp
  src/main/webapp/WEB-INF/views/estimate/estimateCompany.jsp
  src/main/webapp/WEB-INF/views/estimate/estimateOption.jsp
  src/main/webapp/WEB-INF/views/estimate/estimateTotal.jsp
  src/main/webapp/resources/css/customer/signUp.css
  src/main/webapp/resources/css/estimate/estimateCompany.css
  src/main/webapp/resources/css/estimate/estimateTotal.css
  src/main/webapp/resources/js/estimate/estimateTotal.js
Labels: 🕹️ feature, junseok

#66 [PR] BE - 견적함 및 마이페이지 관련 디자인 수정 및 버그 수정
  src/main/java/kr/co/wedder/estimate/controller/EstimateController2.java
  src/main/java/kr/co/wedder/mypage/controller/MyPageController.java
  src/main/resources/mapper/MyPageMapper.xml
  src/main/webapp/WEB-INF/views/mypage/estimateStorage.jsp
  src/main/webapp/WEB-INF/views/mypage/reservationList.jsp
  src/main/webapp/resources/css/common/calendarList.css
  src/main/webapp/resources/css/mypage/estimateStorage.css
  src/main/webapp/resources/css/mypage/myPayment.css
  src/main/webapp/resources/css/mypage/mypage.css
  src/main/webapp/resources/css/mypage/reservationList.css
  src/main/webapp/resources/js/mypage/reservationList.js
Labels: 🕹️ feature, jongwon

#67 [fix] BE - bug fix
  src/main/java/kr/co/wedder/sdmpackage/controller/PackageController.java
  src/main/java/kr/co/wedder/sdmpackage/controller/PackageRestController.java
  src/main/java/kr/co/wedder/sdmpackage/domain/PackageDetailDto.java
  src/main/resources/mapper/PackageMapper.xml
  src/main/webapp/WEB-INF/views/customer/loginForm.jsp
  src/main/webapp/WEB-INF/views/package/packageDetail.jsp
  src/main/webapp/WEB-INF/views/package/packageRecommend.jsp
  src/main/webapp/WEB-INF/views/reservation/sdm/reservationOption.jsp
  src/main/webapp/resources/css/package/packageCalendar.css
  src/main/webapp/resources/css/package/packageDetail.css
  src/main/webapp/resources/css/package/packageMain.css
  src/main/webapp/resources/css/package/packageRecommend.css
  src/main/webapp/resources/js/package/packageCalender.js
  src/main/webapp/resources/js/package/packagePayment.js
  src/main/webapp/resources/js/package/packageRecommend.js
Labels: 🐞 bug, hyewon

#69 [PR] BE - 견적함 이미지 수정 및 CSS 수정
  src/main/webapp/WEB-INF/views/mypage/estimateStorage.jsp
  src/main/webapp/resources/css/mypage/estimateStorage.css
  src/main/webapp/resources/js/map/mapApi.js
Labels: 🐞 bug, junseok
