Repository KOSTA-devops-2team/Wedder, pull requests merged in 2024-08, with the labels that each got.

#13 [PR] BE - Mybatis, Log4j2, Log4JDBC 초기설정
  pom.xml
  src/main/java/kr/co/wedder/user/domain/UserDto.java
  src/main/resources/config/db.properties
  src/main/resources/log4jdbc.log4j2.properties
  src/main/resources/logback.xml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
Labels: hyewon, 📦 config

#14 [PR] BE - JSP 변환 작업 1차 완성
  .classpath
  .project
  pom.xml
  src/main/java/kr/co/wedder/company/controller/SDMController.java
  src/main/java/kr/co/wedder/company/dao/SDMDAO.java
  src/main/java/kr/co/wedder/company/domain/SDMDTO.java
  src/main/java/kr/co/wedder/company/domain/SDMVO.java
  src/main/java/kr/co/wedder/company/service/SDMService.java
  src/main/java/kr/co/wedder/mypage/controller/MyPageController.java
  src/main/java/kr/co/wedder/mypage/dao/MyPageDAO.java
  src/main/java/kr/co/wedder/mypage/domain/MyPageDTO.java
  src/main/java/kr/co/wedder/mypage/service/MyPageService.java
  src/main/java/kr/co/wedder/user/controller/UserController.java
  src/main/webapp/META-INF/MANIFEST.MF
  src/main/webapp/WEB-INF/views/common/calendar.jsp
  src/main/webapp/WEB-INF/views/common/footer.jsp
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/common/sidebarMyPage.jsp
  src/main/webapp/WEB-INF/views/company/dressDetail.jsp
  src/main/webapp/WEB-INF/views/company/dressList.jsp
  src/main/webapp/WEB-INF/views/company/makeupDetail.jsp
  src/main/webapp/WEB-INF/views/company/makeupList.jsp
  src/main/webapp/WEB-INF/views/company/studioDetail.jsp
  src/main/webapp/WEB-INF/views/company/studioList.jsp
  src/main/webapp/WEB-INF/views/mypage/estimateStorage.jsp
  src/main/webapp/WEB-INF/views/mypage/likeList.jsp
  src/main/webapp/WEB-INF/views/mypage/myPayment.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/WEB-INF/views/mypage/paymentDetail.jsp
  src/main/webapp/WEB-INF/views/mypage/reservationDetail.jsp
  src/main/webapp/WEB-INF/views/mypage/reservationList.jsp
  src/main/webapp/WEB-INF/views/mypage/wishList.jsp
  src/main/webapp/WEB-INF/views/user/consentForm.jsp
  src/main/webapp/WEB-INF/views/user/emailVertify.jsp
  src/main/webapp/WEB-INF/views/user/signUp.jsp
  src/main/webapp/resources/css/common/pagination/pagination.html
  src/main/webapp/resources/css/common/pagination/pagination.jsp
  src/main/webapp/resources/css/mypage/calendar.css
  src/main/webapp/resources/js/mypage/calendar.js
Labels: 🕹️ feature, jongwon

#16 [PR] BE - JSP 변환 작업
  .gitignore
  .idea/modules.xml
  src/main/java/kr/co/wedder/company/domain/SDMDTO.java
  src/main/java/kr/co/wedder/company/domain/SDMVO.java
  src/main/java/kr/co/wedder/company/hall/controller/HallController.java
  src/main/java/kr/co/wedder/company/hall/dao/HallDao.java
  src/main/java/kr/co/wedder/company/hall/domain/HallDto.java
  src/main/java/kr/co/wedder/company/hall/service/HallService.java
  src/main/java/kr/co/wedder/company/sdm/controller/SDMController.java
  src/main/java/kr/co/wedder/reservation/hall/controller/VisitHallController.java
  src/main/java/kr/co/wedder/reservation/hall/dao/VisitHallDao.java
  src/main/java/kr/co/wedder/reservation/hall/domain/VisitHallDto.java
  src/main/java/kr/co/wedder/reservation/hall/service/VisitHallService.java
  src/main/java/kr/co/wedder/reservation/sdm/controller/ReservationController.java
  src/main/resources/config/db.properties
  src/main/webapp/WEB-INF/views/company/dress/dressList.jsp
  src/main/webapp/WEB-INF/views/company/makeup/makeupDetail.jsp
  src/main/webapp/WEB-INF/views/company/makeup/makeupList.jsp
  src/main/webapp/WEB-INF/views/company/studio/studioDetail.jsp
  src/main/webapp/WEB-INF/views/company/studio/studioList.jsp
  src/main/webapp/WEB-INF/views/company/weddinghall/mapViewWithFilters.jsp
  src/main/webapp/WEB-INF/views/company/weddinghall/weddinghallDetail.jsp
  src/main/webapp/WEB-INF/views/company/weddinghall/weddinghallList.jsp
  src/main/webapp/WEB-INF/views/company/weddinghall/weddinghallPayment.jsp
  src/main/webapp/WEB-INF/views/reservation/hall/visitSt1.jsp
  src/main/webapp/WEB-INF/views/reservation/hall/visitSt2.jsp
  src/main/webapp/WEB-INF/views/reservation/sdm/reservationDate.jsp
  src/main/webapp/WEB-INF/views/reservation/sdm/reservationOption.jsp
  src/main/webapp/WEB-INF/views/reservation/sdm/reservationPayment.jsp
Labels: 🕹️ feature, jeonghwa
