Repository KOSTA-devops-2team/Wedder, pull requests merged in 2024-09, with the labels that each got.

#25 [PR] BE - 마이페이지 완성
  pom.xml
  src/main/java/kr/co/wedder/calendar/controller/CalendarController.java
  src/main/java/kr/co/wedder/calendar/dao/CalendarDao.java
  src/main/java/kr/co/wedder/calendar/dao/CalendarDaoImpl.java
  src/main/java/kr/co/wedder/calendar/domain/CompanyScheduleDto.java
  src/main/java/kr/co/wedder/calendar/domain/PageResolver.java
  src/main/java/kr/co/wedder/calendar/domain/SearchItem.java
  src/main/java/kr/co/wedder/calendar/domain/TestValidator.java
  src/main/java/kr/co/wedder/calendar/service/CalendarService.java
  src/main/java/kr/co/wedder/calendar/service/CalendarServiceImpl.java
  src/main/java/kr/co/wedder/mypage/controller/MyPageController.java
  src/main/java/kr/co/wedder/mypage/dao/MyPageDAO.java
  src/main/java/kr/co/wedder/mypage/dao/MyPageDaoImpl.java
  src/main/java/kr/co/wedder/mypage/domain/CompanyDto.java
  src/main/java/kr/co/wedder/mypage/domain/HistoryDto.java
  src/main/java/kr/co/wedder/mypage/domain/MyPageDTO.java
  src/main/java/kr/co/wedder/mypage/domain/ReservationDto.java
  src/main/java/kr/co/wedder/mypage/domain/VisitCriteria.java
  src/main/java/kr/co/wedder/mypage/service/MyPageService.java
  src/main/java/kr/co/wedder/mypage/service/MyPageServiceImpl.java
  src/main/java/kr/co/wedder/user/dao/UserDAO.java
  src/main/java/kr/co/wedder/user/dao/UserDaoImpl.java
  src/main/java/kr/co/wedder/user/domain/UserDto.java
  src/main/resources/mapper/CalendarMapper.xml
  src/main/resources/mapper/MyPageMapper.xml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/common/calendar.jsp
  src/main/webapp/WEB-INF/views/common/calendarList.jsp
  src/main/webapp/WEB-INF/views/common/footer.jsp
  src/main/webapp/WEB-INF/views/common/sidebarMyPage.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/WEB-INF/views/mypage/navibar.jsp
  src/main/webapp/WEB-INF/views/mypage/paymentDetail.jsp
  src/main/webapp/WEB-INF/views/mypage/reservationDetail.jsp
  src/main/webapp/WEB-INF/views/mypage/reservationList.jsp
  src/main/webapp/resources/css/common/calendar.css
  src/main/webapp/resources/css/common/calendarList.css
  src/main/webapp/resources/css/common/reset.css
  src/main/webapp/resources/css/mypage/mypage.css
  src/main/webapp/resources/css/mypage/reservationDetail.css
  src/main/webapp/resources/js/main/main.js
  src/main/webapp/resources/js/mypage/calendar.js
  src/main/webapp/resources/js/mypage/myPageMain.js
  src/main/webapp/resources/js/mypage/mypage.js
  src/test/java/kr/co/wedder/calendar/controller/CalendarControllerTest.java
  src/test/java/kr/co/wedder/calendar/dao/CalendarDaoImplTest.java
  src/test/java/kr/co/wedder/calendar/service/CalendarServiceImplTest.java
  src/test/java/kr/co/wedder/mypage/dao/MyPageDaoImplTest.java
  src/test/java/kr/co/wedder/mypage/service/MyPageServiceImplTest.java
Labels: 🕹️ feature, jongwon

#26 [PR] BE - 패키지 라인별 추천
  pom.xml
  src/main/java/kr/co/wedder/packag/PackageController.java
  src/main/java/kr/co/wedder/sdmpackage/controller/PackageController.java
  src/main/java/kr/co/wedder/sdmpackage/controller/PackageRestController.java
  src/main/java/kr/co/wedder/sdmpackage/dao/PackageDao.java
  src/main/java/kr/co/wedder/sdmpackage/dao/PackageDaoImpl.java
  src/main/java/kr/co/wedder/sdmpackage/domain/PackageDetailDto.java
  src/main/java/kr/co/wedder/sdmpackage/domain/PackageDto.java
  src/main/java/kr/co/wedder/sdmpackage/service/PackageService.java
  src/main/java/kr/co/wedder/sdmpackage/service/PackageServiceImpl.java
  src/main/resources/mapper/PackageMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/WEB-INF/views/package/packageDetail.jsp
  src/main/webapp/WEB-INF/views/package/packageMain.jsp
  src/main/webapp/WEB-INF/views/package/packageRecommend.jsp
  src/main/webapp/resources/css/package/packageMain.css
  src/main/webapp/resources/css/package/packageRecommend.css
  src/main/webapp/resources/js/package/packageRecommend.js
Labels: 🕹️ feature, hyewon

#27 [PR] BE - 로그인, 로그아웃
  .idea/dataSources.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jarRepositories.xml
  .idea/jsLibraryMappings.xml
  .idea/webContexts.xml
  pom.xml
  src/main/java/kr/co/wedder/customer/controller/LoginController.java
  src/main/java/kr/co/wedder/customer/controller/RegisterController.java
  src/main/java/kr/co/wedder/customer/dao/CustomerDao.java
  src/main/java/kr/co/wedder/customer/dao/CustomerDaoImpl.java
  src/main/java/kr/co/wedder/customer/domain/CustomerDTO.java
  src/main/java/kr/co/wedder/customer/service/CustomerService.java
  src/main/java/kr/co/wedder/customer/service/CustomerServiceImpl.java
  src/main/java/kr/co/wedder/user/controller/UserController.java
  src/main/java/kr/co/wedder/user/dao/UserDAO.java
  src/main/java/kr/co/wedder/user/domain/UserDto.java
  src/main/java/kr/co/wedder/user/service/UserService.java
  src/main/resources/error_message.properties
  src/main/resources/mapper/CustomerMapper.xml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/reservation/sdm/reservationPayment.jsp
  src/main/webapp/WEB-INF/views/user/loginForm.jsp
  src/main/webapp/WEB-INF/views/user/registerForm.jsp
  src/main/webapp/WEB-INF/views/user/signUp.jsp
  src/main/webapp/resources/css/user/login.css
  src/main/webapp/resources/css/user/signUp.css
  src/main/webapp/resources/js/user/login.js
  src/main/webapp/resources/js/user/signUp.js
  src/test/java/kr/co/wedder/customer/dao/customerDaoTest.java
  src/test/java/kr/co/wedder/customerDaoTest.java
Labels: 🕹️ feature, junseok

#28 [PR] BE - 웨딩홀 리스트 페이지 1차 완성
  .idea/compiler.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/sqldialects.xml
  pom.xml
  src/main/java/kr/co/wedder/company/controller/HallController.java
  src/main/java/kr/co/wedder/company/controller/SDMController.java
  src/main/java/kr/co/wedder/company/dao/CompanyDao.java
  src/main/java/kr/co/wedder/company/dao/CompanyDaoImpl.java
  src/main/java/kr/co/wedder/company/dao/SDMDAO.java
  src/main/java/kr/co/wedder/company/domain/CompanyDto.java
  src/main/java/kr/co/wedder/company/domain/HallDto.java
  src/main/java/kr/co/wedder/company/hall/dao/HallDao.java
  src/main/java/kr/co/wedder/company/hall/domain/HallDto.java
  src/main/java/kr/co/wedder/company/hall/service/HallService.java
  src/main/java/kr/co/wedder/company/service/CompanyService.java
  src/main/java/kr/co/wedder/company/service/CompanyServiceImpl.java
  src/main/java/kr/co/wedder/company/service/SDMService.java
  src/main/java/kr/co/wedder/company/service/SearchItem.java
  src/main/resources/log4jdbc.log4j2.properties
  src/main/resources/mapper/CompanyMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/views/company/weddinghall/weddinghallList.jsp
Labels: 🕹️ feature, jeonghwa

#29 [PR] BE - jongwon git push
  src/main/java/kr/co/wedder/mypage/controller/MyPageController.java
  src/main/java/kr/co/wedder/mypage/dao/MyPageDAO.java
  src/main/java/kr/co/wedder/mypage/dao/MyPageDaoImpl.java
  src/main/java/kr/co/wedder/mypage/domain/CompanyImage.java
  src/main/java/kr/co/wedder/mypage/domain/DressInfo.java
  src/main/java/kr/co/wedder/mypage/domain/MakeupInfo.java
  src/main/java/kr/co/wedder/mypage/domain/OptionDto.java
  src/main/java/kr/co/wedder/mypage/domain/PackageCategoryDto.java
  src/main/java/kr/co/wedder/mypage/domain/ReservationDto.java
  src/main/java/kr/co/wedder/mypage/domain/StudioInfo.java
  src/main/java/kr/co/wedder/mypage/domain/VisitCriteria.java
  src/main/java/kr/co/wedder/mypage/domain/hallInfoDto.java
  src/main/java/kr/co/wedder/mypage/service/MyPageService.java
  src/main/java/kr/co/wedder/mypage/service/MyPageServiceImpl.java
  src/main/java/kr/co/wedder/reservation/hall/controller/VisitHallController.java
  src/main/java/kr/co/wedder/user/dao/UserDAO.java
  src/main/java/kr/co/wedder/user/dao/UserDaoImpl.java
  src/main/java/kr/co/wedder/user/domain/UserDto.java
  src/main/resources/mapper/MyPageMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/mypage/reservationList.jsp
  src/test/java/kr/co/wedder/mypage/dao/MyPageDaoImplTest.java
  src/test/java/kr/co/wedder/mypage/service/MyPageServiceImplTest.java
Labels: 🕹️ feature, jongwon

#32 [PR] BE - 로그인, 비밀번호 구현 및 수정
  .idea/inspectionProfiles/Project_Default.xml
  src/main/java/kr/co/wedder/customer/controller/LoginController.java
  src/main/java/kr/co/wedder/customer/controller/RegisterController.java
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/user/loginForm.jsp
  src/main/webapp/WEB-INF/views/user/registerForm.jsp
  src/main/webapp/resources/js/user/login.js
  src/main/webapp/resources/js/user/signUp.js
Labels: 🕹️ feature, junseok

#31 [PR] BE - 패키지 상세 페이지 및 결제시스템 구현
  .gitignore
  .idea/jsLibraryMappings.xml
  .idea/webContexts.xml
  pom.xml
  src/main/java/kr/co/wedder/config/PayKeysConfig.java
  src/main/java/kr/co/wedder/payment/controller/PaymentController.java
  src/main/java/kr/co/wedder/payment/domain/PaymentDto.java
  src/main/java/kr/co/wedder/payment/domain/PaymentKeysDto.java
  src/main/java/kr/co/wedder/payment/service/PaymentService.java
  src/main/java/kr/co/wedder/payment/service/PaymentServiceImpl.java
  src/main/java/kr/co/wedder/sdmpackage/controller/PackageController.java
  src/main/java/kr/co/wedder/sdmpackage/dao/PackageDaoImpl.java
  src/main/java/kr/co/wedder/sdmpackage/domain/PackageDetailDto.java
  src/main/java/kr/co/wedder/sdmpackage/domain/PackageDto.java
  src/main/java/kr/co/wedder/sdmpackage/service/PackageService.java
  src/main/java/kr/co/wedder/sdmpackage/service/PackageServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mapper/PackageMapper.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/package/packageDetail.jsp
  src/main/webapp/WEB-INF/views/package/packageRecommend.jsp
  src/main/webapp/resources/css/package/packageDetail.css
  src/main/webapp/resources/js/package/packagePayment.js
Labels: 🕹️ feature, hyewon

#34 [PR] BE - 상세 예약 내역 관련 옵션 불러오는 중
  .classpath
  .idea/dataSources.xml
  .idea/misc.xml
  .idea/sqldialects.xml
  .idea/webContexts.xml
  src/main/java/kr/co/wedder/HomeController.java
  src/main/java/kr/co/wedder/calendar/domain/PageResolver.java
  src/main/java/kr/co/wedder/calendar/domain/SearchItem.java
  src/main/java/kr/co/wedder/mypage/controller/MyPageController.java
  src/main/java/kr/co/wedder/mypage/dao/MyPageDao.java
  src/main/java/kr/co/wedder/mypage/dao/MyPageDaoImpl.java
  src/main/java/kr/co/wedder/mypage/domain/CompanyImage.java
  src/main/java/kr/co/wedder/mypage/domain/DressInfo.java
  src/main/java/kr/co/wedder/mypage/domain/HallInfoDto.java
  src/main/java/kr/co/wedder/mypage/domain/HistoryDto.java
  src/main/java/kr/co/wedder/mypage/domain/MakeupInfo.java
  src/main/java/kr/co/wedder/mypage/domain/MyPageDTO.java
  src/main/java/kr/co/wedder/mypage/domain/OptionDto.java
  src/main/java/kr/co/wedder/mypage/domain/PackageCategoryDto.java
  src/main/java/kr/co/wedder/mypage/domain/ReservationDto.java
  src/main/java/kr/co/wedder/mypage/domain/StudioInfo.java
  src/main/java/kr/co/wedder/mypage/domain/VisitCriteria.java
  src/main/java/kr/co/wedder/mypage/service/MyPageService.java
  src/main/java/kr/co/wedder/mypage/service/MyPageServiceImpl.java
  src/main/resources/log4j.xml
  src/main/resources/mapper/MyPageMapper.xml
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/WEB-INF/views/mypage/reservationList.jsp
  src/main/webapp/WEB-INF/views/mypage/wishList.jsp
  src/test/java/kr/co/wedder/mypage/dao/MyPageDaoImplTest.java
  src/test/java/kr/co/wedder/mypage/service/MyPageServiceImplTest.java
Labels: 🕹️ feature, jongwon

#36 [PR] BE - 패키지 검색어 자동완성 및 금액별 필터링
  .idea/dataSources.xml
  .idea/misc.xml
  src/main/java/kr/co/wedder/sdmpackage/controller/PackageController.java
  src/main/java/kr/co/wedder/sdmpackage/controller/PackageRestController.java
  src/main/java/kr/co/wedder/sdmpackage/dao/PackageDao.java
  src/main/java/kr/co/wedder/sdmpackage/dao/PackageDaoImpl.java
  src/main/java/kr/co/wedder/sdmpackage/domain/PackageDetailDto.java
  src/main/java/kr/co/wedder/sdmpackage/service/PackageService.java
  src/main/java/kr/co/wedder/sdmpackage/service/PackageServiceImpl.java
  src/main/resources/mapper/PackageMapper.xml
  src/main/webapp/WEB-INF/views/common/footer.jsp
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/package/packageDetail.jsp
  src/main/webapp/WEB-INF/views/package/packageMain.jsp
  src/main/webapp/WEB-INF/views/package/packageRecommend.jsp
  src/main/webapp/resources/css/common/reset.css
  src/main/webapp/resources/css/package/packageMain.css
  src/main/webapp/resources/css/package/packageRecommend.css
  src/main/webapp/resources/images/package_banner_1.png
  src/main/webapp/resources/js/package/packageMain.js
  src/main/webapp/resources/js/package/packageRecommend.js
  src/test/java/kr/co/wedder/mypage/dao/MyPageDaoImplTest.java
Labels: 🕹️ feature, hyewon

#37 [PR] BE - 업체 검색 기능
  src/main/java/kr/co/wedder/company/controller/HallController.java
  src/main/java/kr/co/wedder/company/controller/HallRestController.java
  src/main/java/kr/co/wedder/company/dao/CompanyDao.java
  src/main/java/kr/co/wedder/company/dao/CompanyDaoImpl.java
  src/main/java/kr/co/wedder/company/domain/CompanyDto.java
  src/main/java/kr/co/wedder/company/domain/DressDto.java
  src/main/java/kr/co/wedder/company/domain/MakeupDto.java
  src/main/java/kr/co/wedder/company/domain/Pagination.java
  src/main/java/kr/co/wedder/company/domain/StudioDto.java
  src/main/java/kr/co/wedder/company/service/CompanyService.java
  src/main/java/kr/co/wedder/company/service/CompanyServiceImpl.java
  src/main/resources/mapper/CompanyMapper.xml
  src/main/webapp/WEB-INF/views/company/weddinghall/weddinghallList.jsp
  src/main/webapp/resources/css/company/weddinghall/weddinghallList.css
  src/main/webapp/resources/js/company/weddinghall/weddinghallList.js
Labels: 🕹️ feature, jeonghwa

#38 [PR] BE - 견적서 1차 완성
  .idea/webContexts.xml
  src/main/java/kr/co/wedder/customer/service/CustomerService.java
  src/main/java/kr/co/wedder/customer/service/CustomerServiceImpl.java
  src/main/java/kr/co/wedder/estimate/EstimateController.java
  src/main/java/kr/co/wedder/estimate/controller/EstimateController.java
  src/main/java/kr/co/wedder/estimate/dao/EstimateDao.java
  src/main/java/kr/co/wedder/estimate/dao/EstimateDaoImpl.java
  src/main/java/kr/co/wedder/estimate/domain/EstimateDto.java
  src/main/java/kr/co/wedder/estimate/service/EstimateService.java
  src/main/java/kr/co/wedder/estimate/service/EstimateServiceImpl.java
  src/main/resources/mapper/CustomerMapper.xml
  src/main/resources/mapper/EstimateMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/estimate/estimateCompany.jsp
  src/main/webapp/resources/css/estimate/estimateCompany.css
  src/main/webapp/resources/js/estimate/estimateCompany.js
Labels: 🕹️ feature, junseok

#40 [PR] BE - 9/30일 세션 연결 및 달력 날짜 변환 고침, 옵션 추가
  .idea/dataSources.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jsLibraryMappings.xml
  .idea/runConfigurations/_template__of_Local.xml
  .idea/webContexts.xml
  pom.xml
  src/main/java/kr/co/wedder/calendar/controller/CalendarController.java
  src/main/java/kr/co/wedder/calendar/controller/CalendarRestController.java
  src/main/java/kr/co/wedder/calendar/domain/CalendarDto.java
  src/main/java/kr/co/wedder/calendar/domain/CompanyScheduleDto.java
  src/main/java/kr/co/wedder/calendar/domain/PageResolver.java
  src/main/java/kr/co/wedder/calendar/domain/SearchItem.java
  src/main/java/kr/co/wedder/company/dao/CompanyDao.java
  src/main/java/kr/co/wedder/estimate/controller/EstimateController2.java
  src/main/java/kr/co/wedder/mypage/controller/MyPageController.java
  src/main/java/kr/co/wedder/mypage/dao/MyPageDao.java
  src/main/java/kr/co/wedder/mypage/dao/MyPageDaoImpl.java
  src/main/java/kr/co/wedder/mypage/domain/DressInfo.java
  src/main/java/kr/co/wedder/mypage/domain/HallInfoDto.java
  src/main/java/kr/co/wedder/mypage/domain/MakeupInfo.java
  src/main/java/kr/co/wedder/mypage/domain/OptionDto.java
  src/main/java/kr/co/wedder/mypage/domain/VisitCriteria.java
  src/main/java/kr/co/wedder/mypage/service/MyPageService.java
  src/main/java/kr/co/wedder/mypage/service/MyPageServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mapper/MyPageMapper.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/views/common/calendar.jsp
  src/main/webapp/WEB-INF/views/common/calendarList.jsp
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/mypage/estimateStorage.jsp
  src/main/webapp/WEB-INF/views/mypage/likeList.jsp
  src/main/webapp/WEB-INF/views/mypage/myPayment.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/WEB-INF/views/mypage/reservationDetail.jsp
  src/main/webapp/WEB-INF/views/mypage/reservationList.jsp
  src/main/webapp/WEB-INF/views/mypage/wishList.jsp
  src/main/webapp/resources/css/common/calendarList.css
  src/main/webapp/resources/css/mypage/reservationDetail.css
  src/main/webapp/resources/js/mypage/calendar.js
  src/main/webapp/resources/js/mypage/reservationDetail.js
  src/main/webapp/resources/js/mypage/reservationList.js
  src/test/java/kr/co/wedder/mypage/dao/MyPageDaoImplTest.java
  src/test/java/kr/co/wedder/mypage/service/MyPageServiceImplTest.java
Labels: 🕹️ feature, jongwon
